# Generated by Django 4.1.7 on 2023-03-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_road_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
