# Generated by Django 4.1.7 on 2023-03-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_road_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('text', models.TextField()),
                ('number_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='road',
            name='reviews',
            field=models.ManyToManyField(to='application.reviews'),
        ),
    ]
