# Generated by Django 4.1.7 on 2023-03-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_reviews_road_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='given_road',
            field=models.TextField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='road',
            name='given_reviews',
            field=models.ManyToManyField(to='application.reviews'),
        ),
    ]
