# Generated by Django 4.1.7 on 2023-03-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_road_reviews_reviews_given_road_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='given_reviews',
            field=models.ManyToManyField(blank=True, to='application.reviews'),
        ),
    ]
