# Generated by Django 4.1.7 on 2023-03-22 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_reviews_text_alter_road_given_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='number_rating',
            field=models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(400)]),
        ),
        migrations.AlterField(
            model_name='road',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
