# Generated by Django 4.1.7 on 2023-03-22 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_reviews_number_rating_alter_reviews_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='given_road',
            field=models.TextField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')]),
        ),
        migrations.AlterField(
            model_name='road',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, default=7, max_digits=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
