# Generated by Django 4.1.7 on 2023-03-22 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_reviews_given_road_alter_road_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=7, max_digits=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
